# Generated by Django 5.2.8 on 2025-11-11 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, help_text='External account identifier', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Account name', max_length=255)),
                ('type', models.CharField(help_text='Account type (e.g., depository, credit, loan)', max_length=100)),
                ('subtype', models.CharField(blank=True, help_text='Account subtype (e.g., checking, savings, credit card)', max_length=100, null=True)),
                ('mask', models.CharField(blank=True, help_text='Last 4 digits of account number', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, help_text='Unique batch identifier (UUID7 - time-ordered, generated by PostgreSQL)', primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, help_text='External request identifier', max_length=255, null=True)),
                ('total_transactions', models.IntegerField(help_text='Total number of transactions in this batch')),
                ('status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed'), ('I', 'processing')], db_index=True, default='P', help_text='Current status of batch processing', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when batch was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when batch was last updated')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='External transaction identifier', max_length=255, unique=True)),
                ('account_id', models.CharField(db_index=True, help_text='Account identifier associated with this transaction', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=19)),
                ('currency', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)])),
                ('date', models.DateTimeField(db_index=True, help_text='Transaction date and time')),
                ('authorized_date', models.DateField(blank=True, help_text='Date the transaction was authorized', null=True)),
                ('merchant_name', models.CharField(blank=True, help_text='Name of the merchant', max_length=255, null=True)),
                ('description', models.TextField(help_text='Transaction description')),
                ('payment_channel', models.CharField(blank=True, help_text='Payment channel (e.g., online, in store, other)', max_length=50, null=True)),
                ('pending', models.BooleanField(default=False, help_text='Whether the transaction is pending')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Transaction category (populated by enrichment)', max_length=100, null=True)),
                ('ingestion_status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed'), ('I', 'processing')], db_index=True, default='P', help_text='Current status of transaction ingestion', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('batch', models.ForeignKey(blank=True, help_text='Batch this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.batch')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['account_id', 'date'], name='core_transa_account_b71ea4_idx'), models.Index(fields=['ingestion_status', 'created_at'], name='core_transa_ingesti_0299e8_idx'), models.Index(fields=['category', 'date'], name='core_transa_categor_914c87_idx')],
            },
        ),
    ]
