# Generated by Django 5.2.8 on 2025-11-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name (e.g., shopping, income, transport)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, help_text='Unique batch identifier', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CategoryPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Pattern to match against merchant name or description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when pattern was created')),
                ('category', models.ForeignKey(help_text='Category this pattern belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='core.category')),
            ],
            options={
                'verbose_name': 'Category Pattern',
                'verbose_name_plural': 'Category Patterns',
                'ordering': ['category__name', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('category', 'pattern'), name='unique_category_pattern')],
            },
        ),
    ]
